### ISSUE TITLE
Override bundle configuration

### ISSUE THREAD

**Issue by SarahCordeau** [Locastic/Loggastic#16]
Hi Paula,

I'm trying to override ElasticSearch index mapping for ActivityLog by using loggastic.yaml file with:

`
    activity_log:
        elastic_properties:
        # .....
            user:
                type: object
                properties:
                    id:
                        type: text
                    username:
                        type: text

`

But when I clear the cache I've got this error 'Invalid type for path "locastic_activity_log.activity_log.elastic_properties". Expected "scalar", but got "array".

Symfony version 6.3.12
PHP version 8.2.19

**Comment by paullla** [comment]
hey @SarahCordeau , the file should look like this:
```yaml
# config/packages/loggastic.yaml
locastic_loggastic:
 activity_log:
    elastic_properties:
      # .....
      user:
        type: object
        properties:
          username:
            type: text
```

Please let me know if this helps
